"statements": [
    {
      "transactions": [
        {
          "date": "01-05-2024",
          "cheque_number": null,
          "particulars": "OPENING BALANCE",
          "payment_method": null,
          "debit": null,
          "credit": "16000.00",
          "balance": "16000.00",
          "category": "Savings and Investments",
          "subcategory": "Savings account deposits",
          "recipientName": null
        },
        {
          "date": "02-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/448973229844/DUSHYANT SO\nPARAS RAM/UPI/HDFC BANK LTD",
          "payment_method": "UPI",
          "debit": "12000.00",
          "credit": null,
          "balance": "4000.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "DUSHYANT SO PARAS RAM"
        },
        {
          "date": "02-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412332348942/SUMIT KUM/Federal\nB/Sent via/",
          "payment_method": "UPI",
          "debit": "1000.00",
          "credit": null,
          "balance": "5000.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": null
        },
        {
          "date": "02-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412332371421/SUMIT KUM/Federal\nB/Sent via/",
          "payment_method": "UPI",
          "debit": "25000.00",
          "credit": null,
          "balance": "30000.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": null
        },
        {
          "date": "02-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412332739237/SUMIT KUM/Federal\nB/Sent via/",
          "payment_method": "UPI",
          "debit": "30000.00",
          "credit": null,
          "balance": "60000.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": null
        },
        {
          "date": "03-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449005189498/Dindugal briyani\nHous/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "50.00",
          "credit": null,
          "balance": "59950.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "Dindugal briyani Hous"
        },
        {
          "date": "03-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449059085721/Dindugal briyani\nHous/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "50.00",
          "credit": null,
          "balance": "59900.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "Dindugal briyani Hous"
        },
        {
          "date": "03-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412410090384/S Rafiq\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "58.00",
          "credit": null,
          "balance": "59842.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "S Rafiq"
        },
        {
          "date": "03-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412465999643/VEERAMMA\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "85.00",
          "credit": null,
          "balance": "59757.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "VEERAMMA"
        },
        {
          "date": "03-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449045803155/CHAKALI SANTHI\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "75.00",
          "credit": null,
          "balance": "59682.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "CHAKALI SANTHI"
        },
        {
          "date": "03-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412442406898/1ST MDP\nFRANCHISEE FO/Genera/ICICI Bank",
          "payment_method": "UPI",
          "debit": "25.00",
          "credit": null,
          "balance": "59657.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "1ST MDP FRANCHISEE FO"
        },
        {
          "date": "03-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412433428028/SANJAY N B\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "80.00",
          "credit": null,
          "balance": "59577.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "SANJAY N B"
        },
        {
          "date": "04-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412593770167/SHABANUM  .\n/UPI/Kotak Mahindra Bank",
          "payment_method": "UPI",
          "debit": "101.00",
          "credit": null,
          "balance": "59476.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "SHABANUM"
        },
        {
          "date": "04-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/449184881230/Abdullah Sharique\n/UPI/IDFC FIRST Bank",
          "payment_method": "UPI",
          "debit": "51.00",
          "credit": null,
          "balance": "59425.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "Abdullah Sharique"
        },
        {
          "date": "04-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449146283223/RANJAN KUMAR M P\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "30.00",
          "credit": null,
          "balance": "59395.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "RANJAN KUMAR M P"
        },
        {
          "date": "04-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412621890771/CAFE AMUDHAM\n/UPI/HDFC BANK LTD",
          "payment_method": "UPI",
          "debit": "70.00",
          "credit": null,
          "balance": "59325.00",
          "category": "Food and Groceries",
          "subcategory": "Dining out",
          "recipientName": "CAFE AMUDHAM"
        },
        {
          "date": "05-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412675704162/N M Madana\n/UPI/State Bank Of India",
          "payment_method": "UPI",
          "debit": "140.00",
          "credit": null,
          "balance": "59185.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "N M Madana"
        },
        {
          "date": "05-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412690503217/REDWANUL HAQUE\nBARBH/UPI/State Bank Of India",
          "payment_method": "UPI",
          "debit": "133.00",
          "credit": null,
          "balance": "59052.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "REDWANUL HAQUE BARBH"
        },
        {
          "date": "05-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449211524338/BLU PEACOCK\nVENTURES /UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "1344.00",
          "credit": null,
          "balance": "57708.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "BLU PEACOCK VENTURES"
        },
        {
          "date": "06-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412761758998/MOUNTAIN TRAIL\nFOODS /Paymen/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "125.00",
          "credit": null,
          "balance": "57583.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "MOUNTAIN TRAIL FOODS"
        },
        {
          "date": "06-05-2024",
          "cheque_number": "836987",
          "particulars": "IF:CAA:FEET RISE VENTURE LLP",
          "payment_method": "Particular",
          "debit": "50000.00",
          "credit": null,
          "balance": "7583.00",
          "category": "Debt Repayment",
          "subcategory": "Loan payments",
          "recipientName": "FEET RISE VENTURE LLP"
        },
        {
          "date": "06-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412791564142/BharatPe Merchant\n/Pay to/YesBank_Yespay",
          "payment_method": "UPI",
          "debit": "40.00",
          "credit": null,
          "balance": "7543.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "BharatPe Merchant"
        },
        {
          "date": "06-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449373491041/Dindugal briyani\nHous/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "50.00",
          "credit": null,
          "balance": "7493.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "Dindugal briyani Hous"
        },
        {
          "date": "06-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449371594909/RANJAN KUMAR M P\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "30.00",
          "credit": null,
          "balance": "7463.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "RANJAN KUMAR M P"
        },
        {
          "date": "07-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449453705886/Kiran Kumar T\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "215.00",
          "credit": null,
          "balance": "7248.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "Kiran Kumar T"
        },
        {
          "date": "07-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412805015971/RRA CAFETERIA LLP\n/UPI/IDFC FIRST Bank",
          "payment_method": "UPI",
          "debit": "113.00",
          "credit": null,
          "balance": "7135.00",
          "category": "Food and Groceries",
          "subcategory": "Dining out",
          "recipientName": "RRA CAFETERIA LLP"
        },
        {
          "date": "07-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412965848914/Swiggy\n/Payvia/Axis Bank Ltd.",
          "payment_method": "UPI",
          "debit": "308.00",
          "credit": null,
          "balance": "6827.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "Swiggy"
        },
        {
          "date": "08-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412994663782/MUNIYAMMAL\nSARAVANAN /UPI/Union Bank of India",
          "payment_method": "UPI",
          "debit": "68.00",
          "credit": null,
          "balance": "6759.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "MUNIYAMMAL SARAVANAN"
        },
        {
          "date": "08-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412954665054/SURENDRA SHETTY\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "120.00",
          "credit": null,
          "balance": "6639.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "SURENDRA SHETTY"
        },
        {
          "date": "08-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/412913870204/SURENDRA SHETTY\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "70.00",
          "credit": null,
          "balance": "6569.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "SURENDRA SHETTY"
        },
        {
          "date": "08-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/449592466207/R SANGEETHA\n/UPI/Canara Bank",
          "payment_method": "UPI",
          "debit": "107.00",
          "credit": null,
          "balance": "6462.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "R SANGEETHA"
        },
        {
          "date": "08-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449563974559/S SATHISH KUMAR\n/Pay to/Federal Bank",
          "payment_method": "UPI",
          "debit": "126.00",
          "credit": null,
          "balance": "6336.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "S SATHISH KUMAR"
        },
        {
          "date": "08-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/412904591276/M VINAY\n/UPI/RBL",
          "payment_method": "UPI",
          "debit": "180.00",
          "credit": null,
          "balance": "6156.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "M VINAY"
        },
        {
          "date": "09-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413022318034/VARGISH  KUMAR\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "35.00",
          "credit": null,
          "balance": "6121.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "VARGISH KUMAR"
        },
        {
          "date": "09-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413042850629/VARALAKSHMI\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "50.00",
          "credit": null,
          "balance": "6071.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "VARALAKSHMI"
        },
        {
          "date": "10-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413106070094/Dindugal briyani\nHous/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "15.00",
          "credit": null,
          "balance": "6056.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "Dindugal briyani Hous"
        },
        {
          "date": "10-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413122270580/1ST MDP\nFRANCHISEE FO/Genera/ICICI Bank",
          "payment_method": "UPI",
          "debit": "25.00",
          "credit": null,
          "balance": "6031.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "1ST MDP FRANCHISEE FO"
        },
        {
          "date": "10-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413160788215/VARALAKSHMI\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "50.00",
          "credit": null,
          "balance": "5981.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "VARALAKSHMI"
        },
        {
          "date": "10-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449736096064/ROHILYA FOODS\nPVT LTD/UPI/HDFC BANK LTD",
          "payment_method": "UPI",
          "debit": "105.00",
          "credit": null,
          "balance": "5876.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "ROHILYA FOODS PVT LTD"
        },
        {
          "date": "11-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413224216584/Dindugal briyani\nHous/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "140.00",
          "credit": null,
          "balance": "5736.00",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "Dindugal briyani Hous"
        },
        {
          "date": "11-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/449808716830/VARADARAJU  G R\n/Pay to/Federal Bank",
          "payment_method": "UPI",
          "debit": "62.00",
          "credit": null,
          "balance": "5674.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "VARADARAJU G R"
        },
        {
          "date": "11-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413273738715/Priya Baheti\n/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "80.00",
          "credit": null,
          "balance": "5594.00",
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "Priya Baheti"
        },
        {
          "date": "12-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/413392465556/Bundl technologies\nPv/Payvia/Airtel Payments Bank",
          "payment_method": "UPI",
          "debit": null,
          "credit": null,
          "balance": null,
          "category": "Miscellaneous",
          "subcategory": null,
          "recipientName": "Bundl technologies Pv"
        }
      ]
    },
    {
      "transactions": [
        {
          "date": "13-05-2024",
          "cheque_number": null,
          "particulars": "Dr Card Charges GST ISSUE",
          "payment_method": "CARD",
          "debit": "354.00",
          "credit": null,
          "balance": "4860.00194",
          "category": "Debt Repayment",
          "subcategory": "Credit card payments",
          "recipientName": null
        },
        {
          "date": "14-05-2024",
          "cheque_number": null,
          "particulars": "NEFT/000147838864/SUMIT KUMAR/ICICI BANK LIMITED//URGENT/",
          "payment_method": "NEFT",
          "debit": null,
          "credit": "100000.00",
          "balance": "104860.00248",
          "category": "Income",
          "subcategory": "Other income sources",
          "recipientName": "SUMIT KUMAR"
        },
        {
          "date": "14-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/450170087368/LALIT  AGGARWAL /UPI/State Bank Of India",
          "payment_method": "UPI",
          "debit": "50000.00",
          "credit": null,
          "balance": "54860.00194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "LALIT  AGGARWAL"
        },
        {
          "date": "14-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/413557588897/LALIT  AGGARWAL /UPI/State Bank Of India",
          "payment_method": "UPI",
          "debit": "50000.00",
          "credit": null,
          "balance": "4860.00194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "LALIT  AGGARWAL"
        },
        {
          "date": "20-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/414154901101/Simpl /UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "1176.27",
          "credit": null,
          "balance": "3683.73194",
          "category": "Shopping",
          "subcategory": "Electronics",
          "recipientName": "Simpl"
        },
        {
          "date": "21-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/450888232131/RRA CAFETERIA LLP /UPI/IDFC FIRST Bank",
          "payment_method": "UPI",
          "debit": "131.00",
          "credit": null,
          "balance": "3552.73194",
          "category": "Food and Groceries",
          "subcategory": "Dining out",
          "recipientName": "RRA CAFETERIA LLP"
        },
        {
          "date": "23-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/414493916807/RAVINA D/O RAJENDER S/UPI/IDBI Bank Limited",
          "payment_method": "UPI",
          "debit": "1000.00",
          "credit": null,
          "balance": "2552.73194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "RAVINA D/O RAJENDER S"
        },
        {
          "date": "23-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2A/451019827141/HEMANTHA KUMAR Y N   /UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "50.00",
          "credit": null,
          "balance": "2502.73194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "HEMANTHA KUMAR Y N"
        },
        {
          "date": "23-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/414493529475/Chaayos /Paymen/Axis Bank Ltd.",
          "payment_method": "UPI",
          "debit": "230.00",
          "credit": null,
          "balance": "2272.73194",
          "category": "Food and Groceries",
          "subcategory": "Food delivery",
          "recipientName": "Chaayos"
        },
        {
          "date": "24-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/451115271521/VARALAKSHMI /UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "40.00",
          "credit": null,
          "balance": "2232.73194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "VARALAKSHMI"
        },
        {
          "date": "24-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/451152581646/KORMANGALA BLR /UPI/HDFC BANK LTD",
          "payment_method": "UPI",
          "debit": "469.00",
          "credit": null,
          "balance": "1763.73194",
          "category": "Transportation",
          "subcategory": "Public transport",
          "recipientName": "KORMANGALA BLR"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/451206040306/Hostinger /Oid133/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "217.04",
          "credit": null,
          "balance": "1546.69194",
          "category": "Housing and Utilities",
          "subcategory": "Internet bill",
          "recipientName": "Hostinger"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/451294326986/Dindugal briyani Hous/UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "100.00",
          "credit": null,
          "balance": "1446.69194",
          "category": "Food and Groceries",
          "subcategory": "Dining out",
          "recipientName": "Dindugal briyani Hous"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/414607833194/RASUL AHMED TAPADAR  /UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "60.00",
          "credit": null,
          "balance": "1386.69194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "RASUL AHMED TAPADAR"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/451202529250/HEMANTH S /UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "100.00",
          "credit": null,
          "balance": "1286.69194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "HEMANTH S"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/451276124040/MULJI AMBABHAI GAMI  /UPI/Yes Bank Ltd",
          "payment_method": "UPI",
          "debit": "60.00",
          "credit": null,
          "balance": "1226.69194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "MULJI AMBABHAI GAMI"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/414622940938/1ST MDP FRANCHISEE FO/Genera/ICICI Bank",
          "payment_method": "UPI",
          "debit": "25.00",
          "credit": null,
          "balance": "1201.69194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "1ST MDP FRANCHISEE FO"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/414610112559/APPLE MED/HDFC BANK/UPI Mand/TEZ",
          "payment_method": "UPI",
          "debit": "5.00",
          "credit": null,
          "balance": "1196.69194",
          "category": "Healthcare",
          "subcategory": "Medical bills",
          "recipientName": "APPLE MED"
        },
        {
          "date": "25-05-2024",
          "cheque_number": null,
          "particulars": "UPI/P2M/451257753907/FBD MALUR /UPI/HDFC BANK LTD",
          "payment_method": "UPI",
          "debit": "260.00",
          "credit": null,
          "balance": "936.69194",
          "category": "Miscellaneous",
          "subcategory": "Gifts and donations",
          "recipientName": "FBD MALUR"
        }
      ]
    }
  ]